project:
  type: website
  output-dir: docs

website:
  title: "GPT데이터 과학"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "소개"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



